config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "watercolors#index"
  
  resources :watercolors, only: [:index, :show]
  resources :albums, only: [:index, :show] do
    resources :sketches, only: :show, shallow: true
  end

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :disciplines, only: [:index, :create, :update, :destroy]
    resources :materials, except: [:show, :new, :edit]
    
    resources :watercolors do
      post :sort, on: :collection
    end
    
    resources :posts do
      resources :comments, shallow: true
    end

    resources :courses do
      resources :lessons, only: [:create, :update, :destroy, :new, :edit], shallow: true
    end
    
    resources :albums do
      resources :sketches, only: [:create, :update, :destroy, :new, :edit], shallow: true
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :sketches, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :description, :began_at, :ended_at, presence: true
  validate :validate_dates_began_greater_than_ended 

  private

  def validate_dates_began_greater_than_ended 
    if began_at.present? && ended_at.present? && (began_at > ended_at) 
      errors.add(:began_at, 'Wrong dates: began after ended!')
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :answers, class_name: "Comment", foreign_key: 'branch_id'
  belongs_to :branch, class_name: "Comment", optional: true

  validates :body, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :discipline
  has_many :lessons, dependent: :destroy

  validates :title, uniqueness: true, presence: true
  validates :title,:description, presence: true
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  has_many :courses, dependent: :nullify
  
  validates :title, presence: true, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :watercolors, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  validates :title, presence: true, uniqueness: true
  validates :title, :description, presence: true

  has_one_attached :preview
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :specifications, dependent: :destroy  
  has_many :sketches, through: :specifications, source: :specificable, source_type: 'Sketch'
  has_many :watercolors, through: :specifications, source: :specificable, source_type: 'Watercolor'

  validates  :title, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/sketch.rb
class Sketch < ApplicationRecord
  belongs_to :album
  has_many :specifications, as: :specificable, dependent: :destroy
  has_many :materials, through: :specifications

  validates :title, :description, :date, presence: true
  validate :validate_date_is_between_dates_of_album

  accepts_nested_attributes_for :specifications, reject_if: :all_blank, allow_destroy: true

  has_one_attached :picture

  private

  def validate_date_is_between_dates_of_album
    if date.present?  && ((date < album.began_at) || (date > album.ended_at)) 
      errors.add(:date, "is not in range of album's period")
    end
  end
end

app/models/specification.rb
class Specification < ApplicationRecord
  belongs_to :material
  belongs_to :specificable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, :lockable,
         :timeoutable, :trackable

  has_many :comments, dependent: :nullify
  
  def admin?
    admin
  end
end

app/models/watercolor.rb
class Watercolor < ApplicationRecord
  belongs_to :genre
  has_many :specifications, as: :specificable, dependent: :destroy
  has_many :materials, through: :specifications

  validates :title, :description, :year, presence: true

  has_one_attached :picture

  accepts_nested_attributes_for :specifications, reject_if: :all_blank, allow_destroy: true

  acts_as_list
end

app/models/wc_genre.rb
class WcGenre < ApplicationRecord
  has_many :watercolors, dependent: :nullify

  validates :title, presence: true
end

app/controllers/admin/materials_controller.rb
class Admin::MaterialsController < Admin::BaseController
  before_action :set_materials, except: :destroy
  before_action :find_material, only: [:update, :destroy]
  
  def index; end

  def create
    @material = Material.new(material_params)
    if @material.save
      redirect_to admin_materials_path, notice: "Material '#{@material.title}' successfully created"
    else
      flash.now[:alert] = "Something went wrong, object was NOT created"
      render :index
    end
  end
  
  def update
    if @material.update_attributes(material_params)
      redirect_to admin_materials_path, notice: "Object was successfully updated"
    else
      flash.now[:alert] = "Something went wrong, object was NOT updated"
      render :index
    end
  end
  
  def destroy
    @material.destroy
    redirect_to admin_materials_path, alert: "Material '#{@material.title}' was deleted"
  end

  private

  def material_params
    params.require(:material).permit(:title)
  end

  def find_material
    @material = Material.find(params[:id])    
  end

  def set_materials
    @materials = Material.all
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_materials, except: :destroy
  before_action :find_material, only: [:update, :destroy]
  
  def index; end

  def create
    @material = Material.new(material_params)
    if @material.save
      redirect_to materials_path, notice: "Material '#{@material.title}' successfully created"
    else
      flash.now[:alert] = "Something went wrong, object was NOT created"
      render :index
    end
  end
  
  def update
    if @material.update_attributes(material_params)
      redirect_to materials_path, notice: "Object was successfully updated"
    else
      flash.now[:alert] = "Something went wrong, object was NOT updated"
      render :index
    end
  end
  
  def destroy
    @material.destroy
    redirect_to materials_path, alert: "Material '#{@material.title}' was deleted"
  end

  private

  def material_params
    params.require(:material).permit(:title)
  end

  def find_material
    @material = Material.find(params[:id])    
  end

  def set_materials
    @materials = Material.all
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def used_materials_list(resource)
    resource.materials.pluck(:title).join(', ')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sketches_helper.rb
module SketchesHelper
end

app/views/admin/materials/_material.html.slim
tr
  td
    = content_tag :span, material.title, class: 'title', data: { resource_id: material.id }
    = render 'admin/shared/form_inline', resource: material == @material ? @material : material
  td.text-right
    .btn-group role="group"
      = link_to "edit", '#', class: 'form-inline-link btn btn-outline-success', data: { resource_id: material.id }
      = link_to "delete", admin_material_path(material), method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' }

app/views/admin/materials/index.html.slim
.row.justify-content-center
  .card.col-sm-8
    .card-header.text-center
      h1 Materials
    .card-body
      = render 'admin/shared/errors', resource: @material
      
      table.table.table-hover
        tbody
          = render @materials if @materials.any?

      hr
      .new-material
        =form_with model: [:admin, Material.new], local: true do |f|
          .input-group
            .input-group-prepend
              span.input-group-text id="inputGroup-sizing-default" a new material:
            =f.text_field :title, class: 'form-control'
            =f.submit 'add', class: 'btn btn-outline-primary', role: 'button'
  

app/views/materials/_material.html.slim
tr
  td
    = content_tag :span, material.title, class: 'title', data: { resource_id: material.id }
    = render 'shared/form_inline', resource: material == @material ? @material : material
  td.text-right
    .btn-group role="group"
      = link_to "edit", '#', class: 'form-inline-link btn btn-outline-success', data: { resource_id: material.id }
      = link_to "delete", material_path(material), method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' }

app/views/materials/index.html.slim
.row.justify-content-center
  .card.col-sm-8
    .card-header.text-center
      h1 Materials
    .card-body
      = render 'shared/errors', resource: @material
      
      table.table.table-hover
        tbody
          = render @materials if @materials.any?

      hr
      .new-material
        =form_with model: Material.new, local: true do |f|
          .input-group
            .input-group-prepend
              span.input-group-text id="inputGroup-sizing-default" a new material:
            =f.text_field :title, class: 'form-control'
            =f.submit 'add', class: 'btn btn-outline-primary', role: 'button'
  