config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "watercolors#index"
  
  resources :watercolors, only: [:index, :show]
  resources :albums, only: [:index, :show] do
    resources :sketches, only: :show, shallow: true
  end

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :disciplines, only: [:index, :create, :update, :destroy]
    resources :materials, except: [:show, :new, :edit]
    
    resources :watercolors do
      post :sort, on: :collection
    end
    
    resources :posts do
      resources :comments, shallow: true
    end

    resources :courses do
      resources :lessons, only: [:create, :update, :destroy, :new, :edit], shallow: true
    end
    
    resources :albums do
      resources :sketches, only: [:create, :update, :destroy, :new, :edit], shallow: true
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :sketches, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :description, :began_at, :ended_at, presence: true
  validate :validate_dates_began_greater_than_ended 

  private

  def validate_dates_began_greater_than_ended 
    if began_at.present? && ended_at.present? && (began_at > ended_at) 
      errors.add(:began_at, 'Wrong dates: began after ended!')
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :answers, class_name: "Comment", foreign_key: 'branch_id'
  belongs_to :branch, class_name: "Comment", optional: true

  validates :body, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :discipline
  has_many :lessons, dependent: :destroy

  validates :title, uniqueness: true, presence: true
  validates :title,:description, presence: true
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  has_many :courses, dependent: :nullify
  
  validates :title, presence: true, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :watercolors, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  validates :title, presence: true, uniqueness: true
  validates :title, :description, presence: true

  has_one_attached :preview
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :specifications, dependent: :destroy  
  has_many :sketches, through: :specifications, source: :specificable, source_type: 'Sketch'
  has_many :watercolors, through: :specifications, source: :specificable, source_type: 'Watercolor'

  validates  :title, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/sketch.rb
class Sketch < ApplicationRecord
  belongs_to :album
  has_many :specifications, as: :specificable, dependent: :destroy
  has_many :materials, through: :specifications

  validates :title, :description, :date, presence: true
  validate :validate_date_is_between_dates_of_album

  accepts_nested_attributes_for :specifications, reject_if: :all_blank, allow_destroy: true

  has_one_attached :picture

  private

  def validate_date_is_between_dates_of_album
    if date.present?  && ((date < album.began_at) || (date > album.ended_at)) 
      errors.add(:date, "is not in range of album's period")
    end
  end
end

app/models/specification.rb
class Specification < ApplicationRecord
  belongs_to :material
  belongs_to :specificable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, :lockable,
         :timeoutable, :trackable

  has_many :comments, dependent: :nullify
  
  def admin?
    admin
  end
end

app/models/watercolor.rb
class Watercolor < ApplicationRecord
  belongs_to :genre
  has_many :specifications, as: :specificable, dependent: :destroy
  has_many :materials, through: :specifications

  validates :title, :description, :year, presence: true

  has_one_attached :picture

  accepts_nested_attributes_for :specifications, reject_if: :all_blank, allow_destroy: true

  acts_as_list
end

app/models/wc_genre.rb
class WcGenre < ApplicationRecord
  has_many :watercolors, dependent: :nullify

  validates :title, presence: true
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController
  def index
    @albums = Album.all
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to admin_albums_path, notice: "New album '#{@album.title}' added successfully"
    else 
      render :new
    end
  end

  def new; end

  def update
    if album.update_attributes(album_params)
      redirect_to admin_albums_path, notice: "The album '#{@album.title}' edited successfully"
    else
      flash.now.alert = 'Uncorrect edition!'
      render :new
    end
  end

  def destroy
    album.destroy
  end

  def edit; end

  def show
    @sketches = album.sketches
  end

  private

  def album
    @album ||= params[:id] ? Album.find(params[:id]) : Album.new
  end

  helper_method :album

  def album_params
    params.require(:album).permit(:title, :description, :began_at, :ended_at)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @sketches = album.sketches
  end

  private

  def album
    @album ||= params[:id] ? Album.find(params[:id]) : Album.new
  end

  helper_method :album
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def used_materials_list(resource)
    resource.materials.pluck(:title).join(', ')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sketches_helper.rb
module SketchesHelper
end

app/views/admin/albums/_album.html.slim
tr.[class="album-#{album.id}"]
  td= album.title
  td= album.sketches.count
  td= album.began_at
  td= album.ended_at
  td  
    .btn-group role="group"
      = link_to 'managing sketches', admin_album_path(album), class: "btn btn-outline-primary" 
      = link_to  'edit', edit_admin_album_path(album), class: "btn btn-outline-success"
      = link_to 'delete', admin_album_path(album), method: :delete, class: "btn btn-outline-danger", remote: true, data: { confirm: 'Are you sure?' }

app/views/admin/albums/_form.html.slim
= render 'admin/shared/errors', resource: album
= form_with model: [:admin, album], local: true  do |f|
  .row
    .col-sm-4
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .col-sm-4
      = f.label :began_at
      = f.date_field :began_at, class: 'form-control'
    .col-sm-4
      = f.label :ended_at
      = f.date_field :ended_at, class: 'form-control'
  = f.label :description
  = f.text_area :description, rows: 5, class: 'form-control'
  br
  = f.submit class: 'btn btn-outline-info'

app/views/admin/albums/destroy.js.erb
$('.album-<%= album.id %>').remove();

app/views/admin/albums/edit.html.slim
.card
  .card-header
    h1 Edit album "#{album.title}"
  .card-body
    =render 'form'

  .card-footer
    = link_to  "back to the albums list", admin_albums_path, class: 'btn btn-secondary'

app/views/admin/albums/index.html.slim
.card
  .card-header.text-center
    h1 Albums
  .card-body
    table.table.table-striped.table-sm.text-center
      thead.table-dark
        tr
          th title
          th number of sketches
          th began at
          th ended at
          th actions
      .tbody
        = render @albums

    .new-album
      h3= link_to image_tag('plus_sm.png'), new_admin_album_path, title: "Add new album"

app/views/admin/albums/new.html.slim
.card
  .card-header
    h1 Add new album
  .card-body
    =render 'form'

  .card-footer
    = link_to  "back to the albums list", admin_albums_path, class: 'btn btn-secondary'

app/views/admin/albums/show.html.slim
.card
  .card-header
    h1 album "#{album.title}"
  .card-body
    .album-info
      p
        strong
          | description:  
        = album.description
      p 
        strong
          | began at:  
        = album.began_at
      p 
        strong
          | ended at:   
        = album.ended_at
    hr
    .sketches
      h3 managing sketches:

      table.table.table-sm.text-center
        thead.table-dark
          th image
          th title
          th description
          th height
          th width
          th date
          th used materials
          th actions
        tbody
          =render @sketches, partial: 'sketches/sketch' if @sketches.any?
      
      p= link_to image_tag("plus_sm.png") , new_admin_album_sketch_path(album), title: 'Add new sketch'


  .card-footer
    = link_to  "back to the albums list", admin_albums_path, class: 'btn btn-secondary'