config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "watercolors#index"
  
  resources :watercolors, only: [:index, :show]
  resources :albums, only: [:index, :show] do
    resources :sketches, only: :show, shallow: true
  end

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :disciplines, only: [:index, :create, :update, :destroy]
    resources :materials, except: [:show, :new, :edit]
    
    resources :watercolors do
      post :sort, on: :collection
    end
    
    resources :posts do
      resources :comments, shallow: true
    end

    resources :courses do
      resources :lessons, only: [:create, :update, :destroy, :new, :edit], shallow: true
    end
    
    resources :albums do
      resources :sketches, only: [:create, :update, :destroy, :new, :edit], shallow: true
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :sketches, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :description, :began_at, :ended_at, presence: true
  validate :validate_dates_began_greater_than_ended 

  private

  def validate_dates_began_greater_than_ended 
    if began_at.present? && ended_at.present? && (began_at > ended_at) 
      errors.add(:began_at, 'Wrong dates: began after ended!')
    end
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :answers, class_name: "Comment", foreign_key: 'branch_id'
  belongs_to :branch, class_name: "Comment", optional: true

  validates :body, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :discipline
  has_many :lessons, dependent: :destroy

  validates :title, uniqueness: true, presence: true
  validates :title,:description, presence: true
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  has_many :courses, dependent: :nullify
  
  validates :title, presence: true, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :watercolors, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  validates :title, presence: true, uniqueness: true
  validates :title, :description, presence: true

  has_one_attached :preview
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :specifications, dependent: :destroy  
  has_many :sketches, through: :specifications, source: :specificable, source_type: 'Sketch'
  has_many :watercolors, through: :specifications, source: :specificable, source_type: 'Watercolor'

  validates  :title, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/sketch.rb
class Sketch < ApplicationRecord
  belongs_to :album
  has_many :specifications, as: :specificable, dependent: :destroy
  has_many :materials, through: :specifications

  validates :title, :description, :date, presence: true
  validate :validate_date_is_between_dates_of_album

  accepts_nested_attributes_for :specifications, reject_if: :all_blank, allow_destroy: true

  has_one_attached :picture

  private

  def validate_date_is_between_dates_of_album
    if date.present?  && ((date < album.began_at) || (date > album.ended_at)) 
      errors.add(:date, "is not in range of album's period")
    end
  end
end

app/models/specification.rb
class Specification < ApplicationRecord
  belongs_to :material
  belongs_to :specificable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, :lockable,
         :timeoutable, :trackable

  has_many :comments, dependent: :nullify
  
  def admin?
    admin
  end
end

app/models/watercolor.rb
class Watercolor < ApplicationRecord
  belongs_to :genre
  has_many :specifications, as: :specificable, dependent: :destroy
  has_many :materials, through: :specifications

  validates :title, :description, :year, presence: true

  has_one_attached :picture

  accepts_nested_attributes_for :specifications, reject_if: :all_blank, allow_destroy: true

  acts_as_list
end

app/models/wc_genre.rb
class WcGenre < ApplicationRecord
  has_many :watercolors, dependent: :nullify

  validates :title, presence: true
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sketches_helper.rb
module SketchesHelper
end

app/views/admin/shared/_errors.html.slim
.errors
  - if resource.present? && resource.errors.any?
    =content_tag :div, class: 'resource-errors', data: { resource_id: resource.id }
      h3 Got #{resource.errors.count} errors!

      ul
        -resource.errors.full_messages.each do |message|
          li= message

app/views/admin/shared/_form_inline.html.slim
= form_with model: [:admin, resource], local: true, class: 'form-inline hide', data: { resource_id: resource.id } do |f|
  .input-group
    .input-group-prepend
      span.input-group-text id="inputGroup-sizing-default" #{resource.class.name}: 
    =f.text_field :title, class: 'form-control'
    =f.submit 'rename', class: 'btn btn-secondary', role: 'button'

app/views/admin/shared/_navigation.html.slim
.container-fluid.text-right
  p
    - if current_user
      = link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary mt-1 mr-1 md-0'

  div class="container"
    div class="navbar justify-content-center"
      a class="navbar-brand" href="/"
        =image_tag 'logo.svg', alt: "dobrulitto logo", height: 100

  nav class="navbar navbar-expand-lg navbar-light bg-white"
    a class="navbar-brand" href="#"
    button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation"
      span class="navbar-toggler-icon"
    
    div class="collapse navbar-collapse" id="navbarToggler"
      div class="container sticky-top bg-white"
        ul class="navbar-nav mr-auto mt-2 mt-lg-0 justify-content-center"
          li class="nav-item"
            a class="nav-link" href="#{admin_posts_path}" Diary
            
          li class="nav-item"
            a class="nav-link" href="#{admin_watercolors_path}" Watercolors

          li class="nav-item"
            a class="nav-link" href="#{admin_albums_path}" Sketching

          li class="nav-item"
            a class="nav-link" href="#{admin_courses_path}" Lessons

          li class="nav-item"
            a class="nav-link" href="#" Contacts

          li class="nav-item"
            a class="nav-link" href="#" Shop

          li class="nav-item dropdown"
            a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" Settings
            div class="dropdown-menu"
              a class="dropdown-item" href="#{admin_genres_path}" Genres
              a class="dropdown-item" href="#{admin_materials_path}" Materials
              a class="dropdown-item" href="#{admin_disciplines_path}" Disciplines

app/views/admin/shared/_specification_fields.html.slim
.nested-fields
  .field
    = f.label :material_id, "material"
    br
    = f.collection_select :material_id, Material.all, :id, :title, prompt: true
  = link_to_remove_association image_tag('minus.png'), f, tite: "remove material"

app/views/shared/_form_inline.html.slim
= form_with model: resource, local: true, class: 'form-inline hide', data: { resource_id: resource.id } do |f|
  .input-group
    .input-group-prepend
      span.input-group-text id="inputGroup-sizing-default" #{resource.class.name}: 
    =f.text_field :title, class: 'form-control'
    =f.submit 'rename', class: 'btn btn-secondary', role: 'button'

app/views/shared/_navigation.html.slim
div class="container-fluid text-right "
  - if current_user
    = link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary mt-1 mr-1 md-0'
  - else
    .btn-group.mt-1.mr-1 role="group"
      = link_to "Sign in", new_user_session_path, class: 'btn btn-outline-secondary '
      = link_to "Sign up", new_user_registration_path, class: 'btn btn-outline-secondary'
  div class="navbar justify-content-center"
    a class="navbar-brand" href="/"
      =image_tag 'logo.svg', alt: "dobrulitto logo", height: 100

  nav class="navbar navbar-expand-lg navbar-light bg-white"
    a class="navbar-brand" href="#"
    button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation"
      span class="navbar-toggler-icon"
    
    div class="collapse navbar-collapse" id="navbarToggler"
      div class="container sticky-top bg-white"
        ul class="navbar-nav mr-auto mt-2 mt-lg-0 justify-content-center"
          li class="nav-item"
            a class="nav-link" href="#{watercolors_path}" Watercolors

          li class="nav-item"
            a class="nav-link" href="#{albums_path}" Sketching

          li class="nav-item"
            a class="nav-link" href="#" Lessons

          li class="nav-item"
            a class="nav-link" href="#{posts_path}" Diary

          li class="nav-item"
            a class="nav-link" href="#" Contacts

          li class="nav-item"
            a class="nav-link" href="#" Shop
          
          - if current_user&.admin?
            li class="nav-item"
              a class="nav-link" href="#{admin_watercolors_path}" Admin Mode